# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e5d9d2e8a9df29faedacb18f4547f0873a010cbe73dc75860d91bd28326f4e1deee87df314e8f5fe3e752481c0addf22a8f66b6fe121a4c28e0d46030f11d5

test:
  secret_key_base: 51f57a0517f1ffae28e88d4c8cfccba1132d2eb72ab2d6d2eb56703355f6c0896bfb118e9fffcae2213cb9e79b5631e6a09db0e25998c49c1a1f6dde357da8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
